name: CI Pipeline
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        run: |
          docker-compose -f docker-compose.yml build

      - name: Tests
        run: |
          docker-compose run --rm web bundle exec rails test

      - name: Linters
        run: |
          docker-compose run --rm web bundle exec rubocop
